"""
Reads a file named packRanges.json generated by readIDRanges.py to locate a rar archive which contains the level id you input,
it then converts it to a gmd file and copies it to your clipboard.

"""

import json
import os
import tempfile
import struct
import rarfile
import win32clipboard

kTagMap = [
    ("kCEK", "static", 4),
    ("k1", "1"),
    ("k23", "15"),
    ("k2", "2"),
    ("k4", "4"),
    ("k3", "3"),
    ("k21", "static", 3),
    ("k16", "5"),
    ("k17", "13"),
    ("k80", "46"),
    ("k81", "47"),
    ("k64", "37"),
    ("k42", "30"),
    ("k45", "35"),
    ("k50", "static", 45),
    ("k48", "45")
]

def findPackKey(packRanges, value):
    closestKey = None
    closestDistance = float("inf")
    for key, rangeData in packRanges.items():
        startId = rangeData["startId"]
        endId = rangeData["endId"]
        if startId <= value <= endId:
            return key
        if value < startId:
            distance = startId - value
        else:
            distance = value - endId
        if distance < closestDistance:
            closestDistance = distance
            closestKey = key
    return closestKey

def parseLevelData(data):
    pairs = {}
    parts = data.strip().split(":")
    for i in range(0, len(parts) - 1, 2):
        key = parts[i]
        value = parts[i + 1].split(";")[0]
        pairs[key] = value
    return pairs

def makeGmd(levelId, pairs):
    xml = ["<?xml version=\"1.0\"?><plist version=\"1.0\" gjver=\"2.0\"><dict>"]
    for kTag, rawKey, *staticValue in kTagMap:
        if rawKey == "static":
            value = staticValue[0]
        else:
            value = pairs.get(rawKey)
        if value is None or value == "":
            continue
        tagType = "s" if kTag in ("k2", "k4", "k3") else "i"
        xml.append(f"<k>{kTag}</k><{tagType}>{value}</{tagType}>")
    xml.append("</dict></plist>")
    return "".join(xml)

def findFileInRar(rarPath, levelId):
    levelPrefix = str(levelId)
    with rarfile.RarFile(rarPath) as archive:
        for info in archive.infolist():
            fileName = os.path.basename(info.filename)
            if fileName.startswith(levelPrefix):
                with archive.open(info) as file:
                    return file.read().decode("utf-8", errors="ignore"), fileName
    return None, None

def copyFileToClipboard(filePath):
    fileList = filePath + "\0"
    fileData = fileList.encode("utf-16le") + b"\0\0"
    dropFiles = struct.pack("IiiII", 20, 0, 0, 0, 1)
    win32clipboard.OpenClipboard()
    try:
        win32clipboard.EmptyClipboard()
        win32clipboard.SetClipboardData(win32clipboard.CF_HDROP, dropFiles + fileData)
    finally:
        win32clipboard.CloseClipboard()

def main():
    with open("packRanges.json", "r", encoding="utf-8") as file:
        packRanges = json.load(file)
    levelId = int(input("Enter level ID: "))
    packNumber = findPackKey(packRanges, levelId)
    print(f"Using pack {packNumber}")
    rarPath = f"Pack {packNumber}.rar"
    rawLevelData, sourceFileName = findFileInRar(rarPath, levelId)
    if rawLevelData is None:
        print(f"Could not find a file starting with {levelId} inside {rarPath}")
        return
    pairs = parseLevelData(rawLevelData)
    gmdContent = makeGmd(str(levelId), pairs)
    if sourceFileName is None:
        return
    baseName = os.path.splitext(sourceFileName)[0]
    gmdFileName = baseName + ".gmd"
    tempDir = tempfile.gettempdir()
    gmdPath = os.path.join(tempDir, gmdFileName)
    with open(gmdPath, "w", encoding="utf-8") as file:
        file.write(gmdContent)
    copyFileToClipboard(gmdPath)
    print(f"Created '{gmdFileName}' and copied it to the clipboard as a file.")

if __name__ == "__main__":
    main()